name: Lint Test
on: [push]
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: build project
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build

      - name: lint check
      - run: npm run lint
