name: Test Pipeline
on: [push]

jobs:
  exploring_all_github_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome message
        run: echo "Welcome ${{ github.actor }}, welcome to the project"

      - name: Print test pipeline message
        run: echo "This is a test pipeline"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List repository contents
        run: |
          echo "The repository: ${{ github.repository }}"
          ls ${{ github.workspace }}

      - name: Print job status
        run: echo "This job's status is ${{ job.status }}"
